name: Terraform

on:
  push:
    branches: [ main ]

jobs:
  terraform:
  
    name: Terraform
    
    runs-on: ubuntu-latest
    
    defaults:
      
      run:
        shell: bash
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_KEY }}
        aws-region: ap-northeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.3

    - name: Execute Terraform
      working-directory: ./services/github
      run: |
        terraform init
        terraform validate
        terraform plan
        terraform apply -auto-approve
      env:
        TF_VAR_GITHUB_APP_ID: ${{ secrets.TF_VAR_GITHUB_APP_ID }}
        TF_VAR_GITHUB_INSTALLATION_ID: ${{ secrets.TF_VAR_GITHUB_INSTALLATION_ID }}
        TF_VAR_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
